src/funrun/history/urls.py
from django.conf.urls import url

from . import views


app_name = 'history'

urlpatterns = [
	url(r'^$', views.sheets, name='sheets'),
	url(r'^sheet/(?P<sheet_id>\d+)/$', views.sheet, name='sheet'),
]

src/funrun/match/urls.py
from django.conf.urls import url

from . import views


app_name = 'match'

urlpatterns = [
	url(r'^$', views.index, name='root'),
	url(r'^match/$', views.start_match, name='start_match'),
	url(r'^match/(?P<match_id>\d+)/$', views.match, name='match'),
	url(r'^match/(?P<match_id>\d+)/round/$', views.round, name='round'),
	url(r'^stats/$', views.month_stats, name='month_stats'),
]

src/funrun/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import django.views.static


admin.autodiscover()

urlpatterns = [
	# robots.txt and friends
	url(r'^([^/]+\.[^/]+)$', django.views.static.serve, {'document_root': settings.STATICFILES_ROOT}),
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('funrun.match.urls')),
	url(r'^history/', include('funrun.history.urls')),
]

if settings.DEBUG and settings.MEDIA_URL.startswith('/'):
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

src/funrun/match/models.py
from django.core.urlresolvers import reverse
from django.db import models, connection
from django.db.models.functions import Coalesce


from funrun.history.models import Match as HMatch, Participation, Place


class Player(models.Model):
	name = models.CharField('Имя', max_length=255)

	class Meta:
		verbose_name = 'Игрок'
		verbose_name_plural = 'Игроки'
		ordering = 'name',

	def __str__(self):
		return self.name

	def get_match_count(self):
		return self.match_set.count() + HMatch.objects.filter(participation__player__name=self.name).count()

	def get_round_count(self):
		return self.round_set.count() + Participation.objects.filter(player__name=self.name).aggregate(victories=Coalesce(models.Sum('victories'), models.expressions.Value(0)))['victories']

	def get_place1_number(self):
		return self.leave_set.filter(place=1).count() + Place.objects.filter(participation__player__name=self.name, number=1).count()

	def get_place2_number(self):
		return self.leave_set.filter(place=2).count() + Place.objects.filter(participation__player__name=self.name, number=2).count()

	def get_place3_number(self):
		return self.leave_set.filter(place=3).count() + Place.objects.filter(participation__player__name=self.name, number=3).count()


class Match(models.Model):
	players = models.ManyToManyField(Player, verbose_name='Игроки')
	start_time = models.DateTimeField('Время начала', auto_now_add=True)
	end_time = models.DateTimeField('Время окончания', null=True, blank=True)

	class Meta:
		verbose_name = 'Матч'
		verbose_name_plural = 'Матчи'
		ordering = '-start_time',

	def __str__(self):
		return 'Матч %d' % self.pk

	def get_stats(self, exclude_winners=False):
		sql = 'SELECT p.id, p.name, (SELECT count(*) FROM match_round r WHERE r.match_id=m.match_id AND r.winner_id=p.id) AS wins, l.place FROM match_player p JOIN match_match_players m ON m.player_id=p.id AND m.match_id=%s LEFT JOIN match_leave l ON l.match_id=m.match_id AND l.player_id=p.id'
		if exclude_winners:
			sql += ' WHERE l.id IS NULL'
		sql += ' ORDER BY p.name'
		cursor = connection.cursor()
		cursor.execute(sql, [self.id])
		return cursor.fetchall()

	def get_duration(self):
		if not self.end_time:
			return ''
		duration = (self.end_time - self.start_time).seconds
		return '%d min' % (duration // 60)


class Round(models.Model):
	match = models.ForeignKey(Match, verbose_name='Матч')
	start_time = models.DateTimeField('Время начала', auto_now_add=True)
	end_time = models.DateTimeField('Время окончания', null=True, blank=True)
	winner = models.ForeignKey(Player, verbose_name='Победитель', null=True, blank=True)

	class Meta:
		verbose_name = 'Раунд'
		verbose_name_plural = 'Раунды'
		ordering = '-start_time',

	def __str__(self):
		return 'Матч %d раунд %d' % (self.match_id, self.get_number())

	def get_number(self):
		return self.match.round_set.filter(start_time__lt=self.start_time).count() + 1


class Leave(models.Model):
	time = models.DateTimeField('Время', auto_now_add=True)
	match = models.ForeignKey(Match, verbose_name='Матч')
	player = models.ForeignKey(Player, verbose_name='Игрок')
	place = models.PositiveSmallIntegerField(u'Место')

	class Meta:
		verbose_name = 'Выход'
		verbose_name_plural = 'Выходы'
		ordering = 'place',

	def __str__(self):
		if self.place > 0:
			return '%s получил %d место в матче %d' % (self.player, self.place, self.match_id)
		else:
			return '%s вышел из матча %d' % (self.player, self.match_id)

src/funrun/match/views.py
from datetime import datetime
from dateutil.relativedelta import relativedelta

from django import forms
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.core.paginator import InvalidPage, EmptyPage, Paginator
from django.utils import timezone

from .models import Match, Player


def paginate_list(request, queryset, per_page):
	try:
		page = int(request.GET.get('page', 1))
	except ValueError:
		page = 1
	paginator = Paginator(queryset, per_page)
	try:
		return paginator.page(page)
	except (EmptyPage, InvalidPage):
		return paginator.page(paginator.num_pages)


def index(request):
	matches = Match.objects.all()
	matches_page = paginate_list(request, matches, settings.MATCHES_PER_PAGE)
	previous_month = datetime.now() - relativedelta(months=1)
	return render(request, "match/index.html", {
		'page': matches_page,
		'month_stats': get_month_stats(),
		'previous_month': previous_month,
	})


def start_match(request):
	match_id = Match.objects.create().id
	return redirect('match:match', match_id=match_id)


class PlayersForm(forms.ModelForm):
	class Meta:
		model = Match
		fields = 'players',


def match(request, match_id):
	match = get_object_or_404(Match, id=match_id)
	players_form = None
	if match.end_time is None:
		players_form = PlayersForm(instance=match, data=request.POST or None)
		if request.method == 'POST':
			finish = request.POST.get('finish')
			update = request.POST.get('update')
			leave = request.POST.get('leave')
			if update and players_form.is_valid():
				players_form.save()
			if leave:
				player = match.players.get(id=leave)
				stats = match.get_stats(exclude_winners=True)
				max_wins = 0
				player_wins = 0
				for record in stats:
					if record[0] == player.id:
						player_wins = record[2]
					if record[2] > max_wins:
						max_wins = record[2]
				if player_wins == max_wins:
					place = match.leave_set.exclude(place=0).count() + 1
				else:
					place = 0
				match.leave_set.create(player=player, place=place)
				if len(match.get_stats(exclude_winners=True)) == 0:
					finish = True
			if finish:
				if match.players.count() < 2:
					match.delete()
					return redirect(index)
				else:
					match.end_time = timezone.now()
					match.save()
			return redirect('match:match', match_id=match.id)
	return render(request, "match/match.html", {
		'match': match,
		'players_form': players_form,
	})


def round(request, match_id):
	match = get_object_or_404(Match, id=match_id)
	if request.method == 'POST':
		round = request.POST.get('round')
		winner = request.POST.get('winner')
		current_round = match.round_set.first()
		if round == 'new':
			new_round = match.round_set.create()
			if match.round_set.filter(winner=None).count() > 1:
				match.round_set.filter(winner=None).exclude(id=new_round.id).delete()
		elif round == 'cancel':
			current_round.winner = None
			current_round.save()
		elif round == 'delete':
			current_round.delete()
		if winner:
			if not match.leave_set.filter(player_id=winner).exists():
				current_round.winner_id = winner
				current_round.end_time = timezone.now()
				current_round.save()
	return redirect('match:match', match_id=match.id)


def get_month_stats(month=None):
	if not month:
		month = datetime.now()
	stats = []
	for player in Player.objects.all():
		stats.append({
			'player': player,
			'match_count': player.match_set.filter(end_time__year=month.year, end_time__month=month.month).count(),
			'round_count': player.round_set.filter(end_time__year=month.year, end_time__month=month.month).count(),
			'place1_number': player.leave_set.filter(place=1, match__end_time__year=month.year, match__end_time__month=month.month).count(),
			'place2_number': player.leave_set.filter(place=2, match__end_time__year=month.year, match__end_time__month=month.month).count(),
			'place3_number': player.leave_set.filter(place=3, match__end_time__year=month.year, match__end_time__month=month.month).count(),
		})
	return stats


def month_stats(request):
	month_string = request.GET.get('month')
	month = datetime.now()
	if month_string:
		month = datetime.strptime(month_string, '%Y-%m')
	previous_month = month - relativedelta(months=1)
	next_month = month + relativedelta(months=1)
	return render(request, "match/month_stats.html", {
		'current_month': month,
		'previous_month': previous_month,
		'next_month': next_month,
		'month_stats': get_month_stats(month),
	})

templates/match/index.html
{% extends "base.html" %}

{% block title %}Статистика / {{ block.super}}{% endblock %}

{% block content %}
<h1>FUN RUN</h1>
<a href="{% url 'match:start_match' %}">Начать новый матч</a>
<h2>Матчи</h2>
{% include "inc/paginator.html" %}
<table class="matches">
	<tr>
		<th>Матч</th>
		<th>Дата</th>
		<th>Игроки</th>
		<th>Раунды</th>
		<th>Время</th>
		<th>Результат</th>
	</tr>
	{% for match in page.object_list %}
		<tr>
			<td><a href="{% url 'match:match' match_id=match.id %}">{{ match }}</a></td>
			<td>{{ match.end_time|date:"d E Y"|default:"Не завершён" }}</td>
			<td>{{ match.players.count }}</td>
			<td>{{ match.round_set.count }}</td>
			<td>{{ match.get_duration }}</td>
			<td>
				<ul>
					{% for leave in match.leave_set.all %}
						{% if leave.place > 0 %}
							<li class="place{{ leave.place }}">{{ leave.place }}: {{ leave.player }}</li>
						{% endif %}
					{% endfor %}
				</ul>
			</td>
		</tr>
	{% endfor %}
</table>
{% include "inc/paginator.html" %}
{% include "match/inc/month_stats.html" %}
<p>
	<a href="{% url 'history:sheets' %}">Заглянуть в историю</a>
</p>
{% endblock %}

templates/match/match.html
{% extends "base.html" %}

{% block title %}Матч {{ match.id }} / {{ block.super}}{% endblock %}

{% block content %}
<a href="{% url 'match:root' %}">На главную</a>
<h1>{{ match }}</h1>
{% if match.end_time %}
	<table>
		<tr>
			<th>Начало</th>
			<td>{{ match.start_time|date:"d E Y, H:i" }}</td>
		</tr>
		<tr>
			<th>Конец</th>
			<td>{{ match.end_time|date:"d E Y, H:i" }}</td>
		</tr>
		<tr>
			<th>Время</th>
			<td>{{ match.get_duration }}</td>
		</tr>
	</table>
	<h2>Статистика</h2>
	<table>
		<tr>
			<th>Игрок</th>
			<th>Победы</th>
			<th>Место</th>
		</tr>
		{% for player in match.get_stats %}
			<tr>
				<td>{{ player.1 }}</td>
				<td>{{ player.2 }}</td>
				<td>
					{% if player.3 != None %}
						{{ player.3|default:'-' }}
					{% endif %}
				</td>
			</tr>
		{% endfor %}
	</table>
	<h2>Раунды</h2>
	<table>
		<tr>
			<th>Раунд</th>
			<th>Время начала</th>
			<th>Время окончания</th>
			<th>Победитель</th>
		</tr>
		{% for round in match.round_set.all %}
			<tr>
				<td>{{ round.get_number }}</td>
				<td>{{ round.start_time|date:"H:i:s" }}</td>
				<td>{{ round.end_time|date:"H:i:s" }}</td>
				<td>{{ round.winner }}</td>
			</tr>
		{% endfor %}
	</table>
{% else %}
	<form action="{% url 'match:match' match.id %}" method="POST">{% csrf_token %}
		<button type="submit" name="finish" value="match" onclick="if (!confirm('Нажмите ОК, если матч окончательно завершён')) return false;">Завершить матч</button>
		<h2>Игроки</h2>
		{{ players_form.as_p }}
		<button type="submit" name="update" value="players">Сохранить изменения</button>
		{% if match.players.count > 1 %}
			<h2>Статистика</h2>
			<table>
				<tr>
					<th>Игрок</th>
					<th>Победы</th>
					<th>Место</th>
				</tr>
				{% for player in match.get_stats %}
					<tr>
						<td>{{ player.1 }}</td>
						<td>{{ player.2 }}</td>
						<td>
							{% if player.3 != None %}
								{{ player.3|default:'-' }}
							{% else %}
								<button type="submit" name="leave" value="{{ player.0 }}" onclick="if (!confirm('Вы уверены, что {{ player.1 }} закончил игру?')) return false;">Закончил</button>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>
		{% endif %}
	</form>
	{% if match.players.count > 1 %}
		<form action="{% url 'match:round' match.id %}" method="POST">{% csrf_token %}
			<h2>Раунды</h2>
			<table>
				<tr>
					<th>Раунд</th>
					<th>Время начала</th>
					<th>Время окончания</th>
					<th>Победитель</th>
					<th>Исправить</th>
				</tr>
				<tr>
					{% if match.round_set.count == 0 or match.round_set.all.0.winner %}
						<td colspan="5">
							<button type="submit" name="round" value="new">Новый раунд</button>
						</td>
					{% endif %}
				</tr>
				{% for round in match.round_set.all %}
					<tr>
						<td>{{ round.get_number }}</td>
						<td>{{ round.start_time|date:"H:i:s" }}</td>
						<td>{{ round.end_time|date:"H:i:s" }}</td>
						<td>
							{% if round.winner %}
								{{ round.winner }}
							{% else %}
								{% for player in match.get_stats %}
									{% if player.3 == None %}
										<button type="submit" name="winner" value="{{ player.0 }}">{{ player.1 }}</button>
										<br />
									{% endif %}
								{% endfor %}
							{% endif %}
						</td>
						<td>
							{% if forloop.counter == 1 %}
								{% if round.winner %}
									<button type="submit" name="round" value="cancel" onclick="if (!confirm('Точно нужно отменить победу {{ round.winner }} в раунде {{ round.get_number }}?')) return false;">Отменить</button>
								{% else %}
									<button type="submit" name="round" value="delete" onclick="if (!confirm('Действительно удалить раунд {{ round.get_number }}?')) return false;">Удалить</button>
								{% endif %}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>
		</form>
	{% endif %}
{% endif %}
{% endblock %}

templates/match/month_stats.html
{% extends "base.html" %}

{% block title %}Статистика за {{ current_month }} / {{ block.super}}{% endblock %}

{% block content %}
<a href="{% url 'match:root' %}">На главную</a>
{% include "match/inc/month_stats.html" %}
{% endblock %}