src/funrun/history/urls.py
from django.conf.urls import url

from . import views


app_name = 'history'

urlpatterns = [
	url(r'^$', views.sheets, name='sheets'),
	url(r'^sheet/(?P<sheet_id>\d+)/$', views.sheet, name='sheet'),
]

src/funrun/match/urls.py
from django.conf.urls import url

from . import views


app_name = 'match'

urlpatterns = [
	url(r'^$', views.index, name='root'),
	url(r'^match/$', views.start_match, name='start_match'),
	url(r'^match/(?P<match_id>\d+)/$', views.match, name='match'),
	url(r'^match/(?P<match_id>\d+)/round/$', views.round, name='round'),
	url(r'^stats/$', views.month_stats, name='month_stats'),
]

src/funrun/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import django.views.static


admin.autodiscover()

urlpatterns = [
	# robots.txt and friends
	url(r'^([^/]+\.[^/]+)$', django.views.static.serve, {'document_root': settings.STATICFILES_ROOT}),
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('funrun.match.urls')),
	url(r'^history/', include('funrun.history.urls')),
]

if settings.DEBUG and settings.MEDIA_URL.startswith('/'):
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

src/funrun/history/models.py
from django.db import models


class Match(models.Model):
	date = models.DateTimeField()


class Player(models.Model):
	name = models.CharField(max_length=254, unique=True)

	def __str__(self):
		return self.name


class Participation(models.Model):
	match = models.ForeignKey(Match)
	player = models.ForeignKey(Player)
	victories = models.PositiveSmallIntegerField()

	class Meta:
		unique_together = 'match', 'player'


class Place(models.Model):
	participation = models.ForeignKey(Participation, unique=True)
	number = models.PositiveSmallIntegerField()


class RaisingRates(models.Model):
	participation = models.ForeignKey(Participation, unique=True)
	count = models.PositiveSmallIntegerField()


class Sheet(models.Model):
	photo = models.ImageField(upload_to='history/facts/', null=True, blank=True)
	rows = models.PositiveSmallIntegerField(null=True, blank=True)
	columns = models.PositiveSmallIntegerField(null=True, blank=True)
	matches = models.ManyToManyField(Match, blank=True)

src/funrun/history/views.py
from django.db import models
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .models import Sheet, Player, Match, Participation

def sheets(request):
	processed = (Sheet.objects
		.filter(matches__isnull=False)
		.annotate(
			from_date=models.Min('matches__date'),
			to_date=models.Max('matches__date')
		)
		.order_by('from_date')
	)
	raw = (Sheet.objects
		.filter(matches__isnull=True)
		.order_by('id')
	)
	return render(request, 'history/sheets.html', context={'processed': processed, 'raw': raw})


def sheet(request, sheet_id):
	from random import choice
	sheet = get_object_or_404(Sheet, id=sheet_id)
	players = list(Player.objects.order_by('id'))
	matches = Match.objects.filter(sheet=sheet).order_by('id')

	rows = []
	for start in range(0, sheet.columns*sheet.rows, sheet.columns):
		row_matches = matches[start:start+sheet.columns]
		header = ['']
		header.extend(timezone.make_naive(match.date).strftime('%d.%m') for match in row_matches)

		data = []
		for player in players:
			victories = [player.name]
			for match in row_matches:
				participation = Participation.objects.filter(player__name=player.name, match=match)
				value = '-'
				if participation.exists():
					v = participation.get().victories
					value = v and '+' * v
				victories.append(value)
			data.append(victories)

		rows.append((header, data))

	return render(request, 'history/sheet.html', context={
		'sheet': sheet,
		'rows': rows,
		'column_width': str(100/(sheet.columns+1)),
		'width': sheet.photo.width,
		'height': sheet.photo.height,
	})

src/funrun/history/templates/history/sheet.html
{% extends "base.html" %}

{% block title %}История / {{ block.super}}{% endblock %}

{% block content %}
<a href="{% url 'history:sheets' %}">К списку листов</a>
<h1>Лист {{ sheet.id }}</h1>
<style>
	#background-switch:checked ~ table {
		background-image: url({{ sheet.photo.url }});
		background-repeat: no-repeat;
		background-size: cover;
	}
</style>
<input id="background-switch" type="checkbox">
<label for="background-switch">Подложить под таблицу оригинал.</label>
<table style="
	width: 100%;
	">
	<tbody>
		{% for headers, data in rows %}
		<tr>
			{% for header in headers %}
			<th style="width: {{ column_width }}%;">{{ header }}</th>
			{% endfor %}
		</tr>
		{% for columns in data %}
		<tr>
			{% for cell in columns %}
			<td style="width: {{ column_width }}%;">{{ cell }}</td>
			{% endfor %}
		</tr>
		{% endfor %}
		{% endfor %}
	</tbody>
</table>
{% endblock %}

src/funrun/history/templates/history/sheets.html
{% extends "base.html" %}

{% block title %}История / {{ block.super}}{% endblock %}

{% block content %}
<a href="{% url 'match:root' %}">На главную</a>
<h1>История</h1>
{% if not processed.exists and not raw.exists %}
<p>
	Соревнования идут без оглядки на историю.
</p>
{% endif %}
{% if processed.exists %}
<h2>Обработанные листы</h2>
<p>
	<ul>
		{% for sheet in processed %}
		<li><a href="{% url 'history:sheet' sheet_id=sheet.id %}">{{ sheet.id }}</a> с {{ sheet.from_date|date }} по {{ sheet.to_date|date }}</li>
		{% endfor %}
	</ul>
</p>
{% endif %}
{% if raw.exists %}
<h2>Необработанные листы</h2>
<p>
	<ul>
		{% for sheet in raw %}
		<li><a href="{% url 'history:sheet' sheet_id=sheet.id %}">{{ sheet.id }}</a></li>
		{% endfor %}
	</ul>
</p>
{% endif %}
{% endblock %}